version: '3.7'

networks:
  app-net:

services:
  app: 
    build: . 
    ports:
      - 80:3000
    networks:
      - app-net
    environment:
      - NODE_ENV=production
  mongodb: 
    image: mongo 
    networks:
      - app-net